### ISSUE TITLE
Packagist Default Version

### ISSUE THREAD

**Issue by caleuanhopkins** [salesforce/handlebars-php#2]
Hey, not sure if you are all aware but the default version from packagist is 2.2.2 which has PHP 7.x breaking code. Your master branch is fine so it might be worth switching packagist to just load that branch instead.

Thanks for putting this library together, real lifesaver 👍

**Comment by Pnoexz** [comment]
Any updates on this?

**Comment by rustybailey** [comment]
Thanks for pointing this out! I created a new release, 2.3.0, with the latest in master and updated Packagist, so the default now points to 2.3.0.
